# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='custom_protocol.proto',
  package='shammam',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x63ustom_protocol.proto\x12\x07shammam\"\"\n\x03Pin\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\"\x16\n\x05State\x12\r\n\x05state\x18\x01 \x01(\x05\"9\n\x0bPinAndState\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty\"\x1b\n\x0bTemperature\x12\x0c\n\x04temp\x18\x01 \x01(\x02\"\x17\n\x06ISRPin\x12\r\n\x05index\x18\x01 \x01(\x05\"A\n\x08ISRState\x12\x0c\n\x04sync\x18\x01 \x01(\x05\x12\x13\n\x0b\x66ull_period\x18\x02 \x01(\x05\x12\x12\n\nwavelength\x18\x03 \x01(\x05\"*\n\x0bISRPinState\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x05\x32\xcd\x02\n\x07\x41rduino\x12-\n\x0bGetPinState\x12\x0c.shammam.Pin\x1a\x0e.shammam.State\"\x00\x12\x35\n\x0bSetPinState\x12\x14.shammam.PinAndState\x1a\x0e.shammam.State\"\x00\x12-\n\tResetPins\x12\x0e.shammam.Empty\x1a\x0e.shammam.Empty\"\x00\x12>\n\x14SetTemperatureSensor\x12\x14.shammam.Temperature\x1a\x0e.shammam.Empty\"\x00\x12\x32\n\x0bGetISRState\x12\x0e.shammam.Empty\x1a\x11.shammam.ISRState\"\x00\x12\x39\n\x0eGetISRPinState\x12\x0f.shammam.ISRPin\x1a\x14.shammam.ISRPinState\"\x00\x62\x06proto3')
)




_PIN = _descriptor.Descriptor(
  name='Pin',
  full_name='shammam.Pin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='shammam.Pin.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='shammam.Pin.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=68,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='shammam.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='shammam.State.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=92,
)


_PINANDSTATE = _descriptor.Descriptor(
  name='PinAndState',
  full_name='shammam.PinAndState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='shammam.PinAndState.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='shammam.PinAndState.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='shammam.PinAndState.state', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=151,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='shammam.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=160,
)


_TEMPERATURE = _descriptor.Descriptor(
  name='Temperature',
  full_name='shammam.Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp', full_name='shammam.Temperature.temp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=189,
)


_ISRPIN = _descriptor.Descriptor(
  name='ISRPin',
  full_name='shammam.ISRPin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='shammam.ISRPin.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=214,
)


_ISRSTATE = _descriptor.Descriptor(
  name='ISRState',
  full_name='shammam.ISRState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sync', full_name='shammam.ISRState.sync', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_period', full_name='shammam.ISRState.full_period', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wavelength', full_name='shammam.ISRState.wavelength', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=281,
)


_ISRPINSTATE = _descriptor.Descriptor(
  name='ISRPinState',
  full_name='shammam.ISRPinState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='shammam.ISRPinState.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='shammam.ISRPinState.state', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=325,
)

DESCRIPTOR.message_types_by_name['Pin'] = _PIN
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['PinAndState'] = _PINANDSTATE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
DESCRIPTOR.message_types_by_name['ISRPin'] = _ISRPIN
DESCRIPTOR.message_types_by_name['ISRState'] = _ISRSTATE
DESCRIPTOR.message_types_by_name['ISRPinState'] = _ISRPINSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pin = _reflection.GeneratedProtocolMessageType('Pin', (_message.Message,), dict(
  DESCRIPTOR = _PIN,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.Pin)
  ))
_sym_db.RegisterMessage(Pin)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.State)
  ))
_sym_db.RegisterMessage(State)

PinAndState = _reflection.GeneratedProtocolMessageType('PinAndState', (_message.Message,), dict(
  DESCRIPTOR = _PINANDSTATE,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.PinAndState)
  ))
_sym_db.RegisterMessage(PinAndState)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURE,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.Temperature)
  ))
_sym_db.RegisterMessage(Temperature)

ISRPin = _reflection.GeneratedProtocolMessageType('ISRPin', (_message.Message,), dict(
  DESCRIPTOR = _ISRPIN,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.ISRPin)
  ))
_sym_db.RegisterMessage(ISRPin)

ISRState = _reflection.GeneratedProtocolMessageType('ISRState', (_message.Message,), dict(
  DESCRIPTOR = _ISRSTATE,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.ISRState)
  ))
_sym_db.RegisterMessage(ISRState)

ISRPinState = _reflection.GeneratedProtocolMessageType('ISRPinState', (_message.Message,), dict(
  DESCRIPTOR = _ISRPINSTATE,
  __module__ = 'custom_protocol_pb2'
  # @@protoc_insertion_point(class_scope:shammam.ISRPinState)
  ))
_sym_db.RegisterMessage(ISRPinState)



_ARDUINO = _descriptor.ServiceDescriptor(
  name='Arduino',
  full_name='shammam.Arduino',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=328,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPinState',
    full_name='shammam.Arduino.GetPinState',
    index=0,
    containing_service=None,
    input_type=_PIN,
    output_type=_STATE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPinState',
    full_name='shammam.Arduino.SetPinState',
    index=1,
    containing_service=None,
    input_type=_PINANDSTATE,
    output_type=_STATE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResetPins',
    full_name='shammam.Arduino.ResetPins',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTemperatureSensor',
    full_name='shammam.Arduino.SetTemperatureSensor',
    index=3,
    containing_service=None,
    input_type=_TEMPERATURE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetISRState',
    full_name='shammam.Arduino.GetISRState',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ISRSTATE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetISRPinState',
    full_name='shammam.Arduino.GetISRPinState',
    index=5,
    containing_service=None,
    input_type=_ISRPIN,
    output_type=_ISRPINSTATE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARDUINO)

DESCRIPTOR.services_by_name['Arduino'] = _ARDUINO

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ArduinoStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetPinState = channel.unary_unary(
          '/shammam.Arduino/GetPinState',
          request_serializer=Pin.SerializeToString,
          response_deserializer=State.FromString,
          )
      self.SetPinState = channel.unary_unary(
          '/shammam.Arduino/SetPinState',
          request_serializer=PinAndState.SerializeToString,
          response_deserializer=State.FromString,
          )
      self.ResetPins = channel.unary_unary(
          '/shammam.Arduino/ResetPins',
          request_serializer=Empty.SerializeToString,
          response_deserializer=Empty.FromString,
          )
      self.SetTemperatureSensor = channel.unary_unary(
          '/shammam.Arduino/SetTemperatureSensor',
          request_serializer=Temperature.SerializeToString,
          response_deserializer=Empty.FromString,
          )
      self.GetISRState = channel.unary_unary(
          '/shammam.Arduino/GetISRState',
          request_serializer=Empty.SerializeToString,
          response_deserializer=ISRState.FromString,
          )
      self.GetISRPinState = channel.unary_unary(
          '/shammam.Arduino/GetISRPinState',
          request_serializer=ISRPin.SerializeToString,
          response_deserializer=ISRPinState.FromString,
          )


  class ArduinoServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetPinState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SetPinState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ResetPins(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SetTemperatureSensor(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetISRState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetISRPinState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ArduinoServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetPinState': grpc.unary_unary_rpc_method_handler(
            servicer.GetPinState,
            request_deserializer=Pin.FromString,
            response_serializer=State.SerializeToString,
        ),
        'SetPinState': grpc.unary_unary_rpc_method_handler(
            servicer.SetPinState,
            request_deserializer=PinAndState.FromString,
            response_serializer=State.SerializeToString,
        ),
        'ResetPins': grpc.unary_unary_rpc_method_handler(
            servicer.ResetPins,
            request_deserializer=Empty.FromString,
            response_serializer=Empty.SerializeToString,
        ),
        'SetTemperatureSensor': grpc.unary_unary_rpc_method_handler(
            servicer.SetTemperatureSensor,
            request_deserializer=Temperature.FromString,
            response_serializer=Empty.SerializeToString,
        ),
        'GetISRState': grpc.unary_unary_rpc_method_handler(
            servicer.GetISRState,
            request_deserializer=Empty.FromString,
            response_serializer=ISRState.SerializeToString,
        ),
        'GetISRPinState': grpc.unary_unary_rpc_method_handler(
            servicer.GetISRPinState,
            request_deserializer=ISRPin.FromString,
            response_serializer=ISRPinState.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'shammam.Arduino', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaArduinoServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetPinState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SetPinState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ResetPins(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SetTemperatureSensor(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetISRState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetISRPinState(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaArduinoStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetPinState(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetPinState.future = None
    def SetPinState(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SetPinState.future = None
    def ResetPins(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    ResetPins.future = None
    def SetTemperatureSensor(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SetTemperatureSensor.future = None
    def GetISRState(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetISRState.future = None
    def GetISRPinState(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetISRPinState.future = None


  def beta_create_Arduino_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('shammam.Arduino', 'GetISRPinState'): ISRPin.FromString,
      ('shammam.Arduino', 'GetISRState'): Empty.FromString,
      ('shammam.Arduino', 'GetPinState'): Pin.FromString,
      ('shammam.Arduino', 'ResetPins'): Empty.FromString,
      ('shammam.Arduino', 'SetPinState'): PinAndState.FromString,
      ('shammam.Arduino', 'SetTemperatureSensor'): Temperature.FromString,
    }
    response_serializers = {
      ('shammam.Arduino', 'GetISRPinState'): ISRPinState.SerializeToString,
      ('shammam.Arduino', 'GetISRState'): ISRState.SerializeToString,
      ('shammam.Arduino', 'GetPinState'): State.SerializeToString,
      ('shammam.Arduino', 'ResetPins'): Empty.SerializeToString,
      ('shammam.Arduino', 'SetPinState'): State.SerializeToString,
      ('shammam.Arduino', 'SetTemperatureSensor'): Empty.SerializeToString,
    }
    method_implementations = {
      ('shammam.Arduino', 'GetISRPinState'): face_utilities.unary_unary_inline(servicer.GetISRPinState),
      ('shammam.Arduino', 'GetISRState'): face_utilities.unary_unary_inline(servicer.GetISRState),
      ('shammam.Arduino', 'GetPinState'): face_utilities.unary_unary_inline(servicer.GetPinState),
      ('shammam.Arduino', 'ResetPins'): face_utilities.unary_unary_inline(servicer.ResetPins),
      ('shammam.Arduino', 'SetPinState'): face_utilities.unary_unary_inline(servicer.SetPinState),
      ('shammam.Arduino', 'SetTemperatureSensor'): face_utilities.unary_unary_inline(servicer.SetTemperatureSensor),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Arduino_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('shammam.Arduino', 'GetISRPinState'): ISRPin.SerializeToString,
      ('shammam.Arduino', 'GetISRState'): Empty.SerializeToString,
      ('shammam.Arduino', 'GetPinState'): Pin.SerializeToString,
      ('shammam.Arduino', 'ResetPins'): Empty.SerializeToString,
      ('shammam.Arduino', 'SetPinState'): PinAndState.SerializeToString,
      ('shammam.Arduino', 'SetTemperatureSensor'): Temperature.SerializeToString,
    }
    response_deserializers = {
      ('shammam.Arduino', 'GetISRPinState'): ISRPinState.FromString,
      ('shammam.Arduino', 'GetISRState'): ISRState.FromString,
      ('shammam.Arduino', 'GetPinState'): State.FromString,
      ('shammam.Arduino', 'ResetPins'): Empty.FromString,
      ('shammam.Arduino', 'SetPinState'): State.FromString,
      ('shammam.Arduino', 'SetTemperatureSensor'): Empty.FromString,
    }
    cardinalities = {
      'GetISRPinState': cardinality.Cardinality.UNARY_UNARY,
      'GetISRState': cardinality.Cardinality.UNARY_UNARY,
      'GetPinState': cardinality.Cardinality.UNARY_UNARY,
      'ResetPins': cardinality.Cardinality.UNARY_UNARY,
      'SetPinState': cardinality.Cardinality.UNARY_UNARY,
      'SetTemperatureSensor': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'shammam.Arduino', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
