
class CONTROLLERS_CONFIG:
    LEGACY_MODE = False
    SOCKET_SERVER_BIND_PORT = 4567
    SOCKET_SERVER_MAX_CONNECTIONS = 20
    SOCKET_SERVER_RECONNECT_TIMEOUT = 2.0
    SOCKET_HOSTING_INTERCACES = ["eth0", "eth1", "wlan0", "wlan1", "en0", "en1"]
